<?php

/**
 * bsdApiUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class bsdApiUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object bsdApiUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('bsdApiUser');
    }
}