<?php

/**
 * bsdApiUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    UncleJoey
 * @subpackage model
 * @author     druid628
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class bsdApiUser extends BasebsdApiUser
{
}
