<?php

/**
 * bsdApiUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    UncleJoey
 * @subpackage model
 * @author     druid628
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PluginBsdApiUser extends PluginBaseBsdApiUser {

	protected function generateApiKey()
	{
		if (sfContext::hasInstance())
		{
			$un = sfContext::getInstance()->getUser()->getGuardUser()->getUsername();
			$rannums = rand('42809', '62882');

			$hash1 = hash('md5', $un);
			$hash2 = hash('md5', $rannums);

			$hash1Array = $this->breakHashInTwo($hash1);
			$hash2Array = $this->breakHashInTwo($hash2);

			return $hash1Array["right"] . $hash2Array["left"];
		}
	}

	protected function breakHashInTwo($hashToBreak)
	{
			$half = (int) ( (strlen($hashToBreak) / 2) ); // cast to int incase str length is odd
			$left = substr($hashToBreak, 0, $half);
			$right = substr($hashToBreak, $half);

			return array("left" => $left, "right" => $right);
	}

	public function reGenKey()
	{
		$this->api_key = $this->generateApiKey();
	}

	public function save(Doctrine_Connection $conn = null)
	{
		if (is_null($this->api_key) || $this->api_key == "")
		{
			$this->api_key = $this->generateApiKey();
		}
		parent::save($conn);
	}

}
