api_learn:
  url: /api/learn_me
  param: { module: bsdApiControl, action: learnMe }

api_signup:
  url: /api/signUp
  param: { module: bsdApiControl, action: new }

api_deauth:
  url: /api/revoke/:token
  param: { module: bsdApi, action: revoke }

api_get:
  url: /api/get/:token/:appClass/*
  param: { module: bsdApi, action: get }

api_give:
  url: /api/give/:token/:isNew/:appClass/*
  param: { module: bsdApi, action: give }